travis:
  secure:
    BINSTAR_TOKEN: JzMao2h2XxT2NPYQF4mVUulAgtUuimJyV1STmUkTS+edmnRhRpwfn3G0Yh7ridqz3+Sp0O/AiQVCE2+NBzhajgx7pdWPPFOluzspff/quKYjrsxfYaCKXY2qzFSa1zekX/HoLSNRDwGvyK0TE/nVQ8m1sJqPDH0y8G+46ICA2mo0NnTK/2yMVg4wMM2QH160Iuhyvt18nqIK7WduGluZRdbPD10xz8FnqybSZmxUqJMxWodX4RFZOBPprndTV4S+mEtTTN3ziFDEM1VXh2EGdXpMC0/fnMeLed0/qhUFxsvKNgFwFSA5eM/wTJUaGZur08g0h9FbrjfBtyFnZvLgnlNv1awJOAGUq76sqq0nm5sBBotsLLjoNBeujLUxuRwC4Xal3u9zLjATE7ZJZBpC3YaR0P91DRP3vouq8vLyKu1p3Wh5Q3YLe/98GDE7DhsUdGnmyKl4Iq1XlNdkfbyuaDRfgOzhYsYCilXTwT0ouLdMd6fl4Cgm7fYP02+HAhuzg7FxDod0F71WHU7a4B7CqMMGO7keNdqAOwjeny0pmecJAANpPjcpWIXh6C8f47mB1ezSJJsNstwrAKIgi4YjjoHH8Y4CTpU+m9yRKgwBB1zjWtd7bgPO+6GfEhZzHcHbEVsjO/e6ROFvFlowD83F7liAsMICric/tpNCCu7AHHs=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
